<?php

namespace Container7IDRPvU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GN5J0qkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GN5J0qk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GN5J0qk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'newsletter' => ['privates', '.errored..service_locator.GN5J0qk.App\\Entity\\Newsletter', NULL, 'Cannot autowire service ".service_locator.GN5J0qk": it references class "App\\Entity\\Newsletter" but no such service exists.'],
        ], [
            'manager' => '?',
            'newsletter' => 'App\\Entity\\Newsletter',
        ]);
    }
}
