<?php

namespace Container7IDRPvU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BJL9NdoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bJL9Ndo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bJL9Ndo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'serviceCommande' => ['privates', 'App\\Service\\ServiceCommande', 'getServiceCommandeService', true],
        ], [
            'serviceCommande' => 'App\\Service\\ServiceCommande',
        ]);
    }
}
