<?php

namespace Container7IDRPvU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProducteursService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Tpcd01Z.App\Entity\Producteurs' shared service.
     *
     * @return \App\Entity\Producteurs
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Tpcd01Z": it references class "App\\Entity\\Producteurs" but no such service exists.');
    }
}
