<?php

namespace ContainerQpTRCQG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EMI6ndwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EMI6ndw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EMI6ndw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'serviceCommande' => ['privates', 'App\\Service\\ServiceCommande', 'getServiceCommandeService', true],
            'session' => ['services', 'session', 'getSessionService', true],
        ], [
            'manager' => '?',
            'serviceCommande' => 'App\\Service\\ServiceCommande',
            'session' => '?',
        ]);
    }
}
