<?php

namespace ContainerQpTRCQG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Tpcd01ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Tpcd01Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Tpcd01Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'producteur' => ['privates', '.errored..service_locator.Tpcd01Z.App\\Entity\\Producteurs', NULL, 'Cannot autowire service ".service_locator.Tpcd01Z": it references class "App\\Entity\\Producteurs" but no such service exists.'],
        ], [
            'producteur' => 'App\\Entity\\Producteurs',
        ]);
    }
}
