<?php

namespace ContainerQpTRCQG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QTAx_HaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qTAx.ha' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qTAx.ha'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commandes' => ['privates', '.errored..service_locator.qTAx.ha.App\\Entity\\Commande', NULL, 'Cannot autowire service ".service_locator.qTAx.ha": it references class "App\\Entity\\Commande" but no such service exists.'],
        ], [
            'commandes' => 'App\\Entity\\Commande',
        ]);
    }
}
