<?php

namespace ContainerQpTRCQG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N_Axm49Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.n.axm49' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.n.axm49'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commandeRepository' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'paniersRepository' => ['privates', 'App\\Repository\\PaniersRepository', 'getPaniersRepositoryService', true],
            'producteursRepository' => ['privates', 'App\\Repository\\ProducteursRepository', 'getProducteursRepositoryService', true],
            'produitsRepository' => ['privates', 'App\\Repository\\ProduitsRepository', 'getProduitsRepositoryService', true],
            'quantityCommandRepository' => ['privates', 'App\\Repository\\QuantityCommandRepository', 'getQuantityCommandRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'commandeRepository' => 'App\\Repository\\CommandeRepository',
            'manager' => '?',
            'paniersRepository' => 'App\\Repository\\PaniersRepository',
            'producteursRepository' => 'App\\Repository\\ProducteursRepository',
            'produitsRepository' => 'App\\Repository\\ProduitsRepository',
            'quantityCommandRepository' => 'App\\Repository\\QuantityCommandRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
