<?php

namespace ContainerQpTRCQG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IRXhcBXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IRXhcBX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IRXhcBX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paniers' => ['privates', '.errored..service_locator.IRXhcBX.App\\Entity\\Paniers', NULL, 'Cannot autowire service ".service_locator.IRXhcBX": it references class "App\\Entity\\Paniers" but no such service exists.'],
        ], [
            'paniers' => 'App\\Entity\\Paniers',
        ]);
    }
}
