<?php

namespace ContainerQpTRCQG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsletterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.GN5J0qk.App\Entity\Newsletter' shared service.
     *
     * @return \App\Entity\Newsletter
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.GN5J0qk": it references class "App\\Entity\\Newsletter" but no such service exists.');
    }
}
